# Mapa interativo das capitais do Brasil

Integrantes:

- Luiz Henrique
- Paulo Henrique

## Objetivo do trabalho

Integrar todos os conceitos trabalhados pelos grupos anteriores.

## 1) Bibliotecas usadas

Usamos as seguintes bibliotecas `pandas`, `folium` para criar o mapa.

In [ ]:
%pip install pandas 
%pip install folium

Requirement already satisfied: pandas in c:\users\pichau\appdata\local\python\pythoncore-3.14-64\lib\site-packages (3.0.3)
Requirement already satisfied: numpy>=2.3.3 in c:\users\pichau\appdata\local\python\pythoncore-3.14-64\lib\site-packages (from pandas) (2.4.6)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\pichau\appdata\roaming\python\python314\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in c:\users\pichau\appdata\local\python\pythoncore-3.14-64\lib\site-packages (from pandas) (2026.2)
Requirement already satisfied: six>=1.5 in c:\users\pichau\appdata\roaming\python\python314\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.3 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip

^C
Note: you may need to restart the kernel to use updated packages.

Requirement already satisfied: folium in c:\users\pichau\appdata\local\python\pythoncore-3.14-64\lib\site-packages (0.20.0)
Requirement already satisfied: branca>=0.6.0 in c:\users\pichau\appdata\local\python\pythoncore-3.14-64\lib\site-packages (from folium) (0.8.2)
Requirement already satisfied: jinja2>=2.9 in c:\users\pichau\appdata\local\python\pythoncore-3.14-64\lib\site-packages (from folium) (3.1.6)
Requirement already satisfied: numpy in c:\users\pichau\appdata\local\python\pythoncore-3.14-64\lib\site-packages (from folium) (2.4.6)
Requirement already satisfied: requests in c:\users\pichau\appdata\local\python\pythoncore-3.14-64\lib\site-packages (from folium) (2.34.2)
Requirement already satisfied: xyzservices in c:\users\pichau\appdata\local\python\pythoncore-3.14-64\lib\site-packages (from folium) (2026.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in c:\users\pichau\appdata\local\python\pythoncore-3.14-64\lib\site-packages (from jinja2>=2.9->folium) (3.0.3)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\users\pichau\appdata\local\python\pythoncore-3.14-64\lib\site-packages (from requests->folium) (3.4.7)
Requirement already satisfied: idna<4,>=2.5 in c:\users\pichau\appdata\local\python\pythoncore-3.14-64\lib\site-packages (from requests->folium) (3.18)
Requirement already satisfied: urllib3<3,>=1.26 in c:\users\pichau\appdata\local\python\pythoncore-3.14-64\lib\site-packages (from requests->folium) (2.7.0)
Requirement already satisfied: certifi>=2023.5.7 in c:\users\pichau\appdata\local\python\pythoncore-3.14-64\lib\site-packages (from requests->folium) (2026.5.20)

[notice] A new release of pip is available: 25.3 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [4]:
import pandas as pd
import folium

## 2) leitura do arquivo CSV

O arquivo CSV é a nossa base de dados que foi feita com dados do ibge.

In [5]:
df = pd.read_csv("capitais_brasil_ibge.csv")

df.head()

,capital,uf,estado,regiao,latitude,longitude,fonte,link_fonte
0,Rio Branco,AC,Acre,Norte,-9.97499,-67.8243,IBGE - Localidades do Brasil / Censo Demográfi...,https://www.ibge.gov.br/geociencias/organizaca...
1,Maceió,AL,Alagoas,Nordeste,-9.66599,-35.7350,IBGE - Localidades do Brasil / Censo Demográfi...,https://www.ibge.gov.br/geociencias/organizaca...
2,Macapá,AP,Amapá,Norte,0.03493,-51.0694,IBGE - Localidades do Brasil / Censo Demográfi...,https://www.ibge.gov.br/geociencias/organizaca...
3,Manaus,AM,Amazonas,Norte,-3.11866,-60.0212,IBGE - Localidades do Brasil / Censo Demográfi...,https://www.ibge.gov.br/geociencias/organizaca...
4,Salvador,BA,Bahia,Nordeste,-12.97140,-38.5014,IBGE - Localidades do Brasil / Censo Demográfi...,https://www.ibge.gov.br/geociencias/organizaca...

## 3) entendendo a estrutura dos dados

- Aqui vamos entender a tabela.

    - quantidade de linhas e colunas
    - nomes das colunas
    - os tipos dos dados
    - se tem valores vazios

In [8]:
print("linhas e colunas:", df.shape)

print("\ncolunas da tabela:")
print(df.columns)

print("\ntipos dos dados:")
print(df.dtypes)

print("\nvalores vazios por coluna:")
print(df.isnull().sum())

linhas e colunas: (27, 8)

colunas da tabela:
Index(['capital', 'uf', 'estado', 'regiao', 'latitude', 'longitude', 'fonte',
       'link_fonte'],
      dtype='str')

tipos dos dados:
capital           str
uf                str
estado            str
regiao            str
latitude      float64
longitude     float64
fonte             str
link_fonte        str
dtype: object

valores vazios por coluna:
capital       0
uf            0
estado        0
regiao        0
latitude      0
longitude     0
fonte         0
link_fonte    0
dtype: int64

# 4) filtro por região

Aqui vamos criar um filtro para visualizar apenas as capitais de uma região.

Você pode trocar o valor de `regiao_escolhida` para:

- Sul -------------> 3 estados
- Norte ----------> 7 estados
- Sudeste -------> 4 estados
- Nordeste ------> 9 estados
- Centro-Oeste -> 4 estados

In [ ]:
# escolhemos a região
regiao_escolhida = "Centro-Oeste"

# faz um novo df apenas com a região escolhida
df_filtrado = df[df["regiao"] == regiao_escolhida]

# aqui mostrar o resultado
df_filtrado

,capital,uf,estado,regiao,latitude,longitude,fonte,link_fonte
6,Brasília,DF,Distrito Federal,Centro-Oeste,-15.7939,-47.8828,IBGE - Localidades do Brasil / Censo Demográfi...,https://www.ibge.gov.br/geociencias/organizaca...
8,Goiânia,GO,Goiás,Centro-Oeste,-16.6864,-49.2643,IBGE - Localidades do Brasil / Censo Demográfi...,https://www.ibge.gov.br/geociencias/organizaca...
10,Cuiabá,MT,Mato Grosso,Centro-Oeste,-15.6010,-56.0974,IBGE - Localidades do Brasil / Censo Demográfi...,https://www.ibge.gov.br/geociencias/organizaca...
11,Campo Grande,MS,Mato Grosso do Sul,Centro-Oeste,-20.4486,-54.6295,IBGE - Localidades do Brasil / Censo Demográfi...,https://www.ibge.gov.br/geociencias/organizaca...

## 5) criando o mapa interativo com folium

### o que faz o folium

- ele é uma biblioteca Python usada para criar mapas interativos, permitindo adicionar marcadores, pop-ups e camadas no mapa.

In [ ]:
# aqui acontece a criação do mapa centralizado no Brasil
mapa = folium.Map(
    location=[-14.2350, -51.9253],
    zoom_start=4
)

# adicionamos capitais como um marcador no mapa
for linha in df.itertuples():

    # aqui faremos o que vai aparecer quando clicar no marcador
    texto_popup = f"""
    <b>{linha.capital}</b><br>
    Estado: {linha.estado}<br>
    UF: {linha.uf}<br>
    Região: {linha.regiao}<br>
    Latitude: {linha.latitude}<br>
    Longitude: {linha.longitude}
    """

    # fizemos o marcador no mapa
    folium.Marker(
        location=[linha.latitude, linha.longitude],
        popup=texto_popup,
        tooltip=linha.capital
    ).add_to(mapa)

# mostra a pre-visualização
mapa

# 6) adicionando o filtro

Aqui fizemos o mesmo codigo, no entanto adicionando os filtros

In [ ]:

mapa_regioes = folium.Map(
    location=[-14.2350, -51.9253],
    zoom_start=4
)

# aqui faremos uma camada para cada região
for regiao in df["regiao"].unique():

    # usamos o FeatureGroup para conseguir criar um grupo de marcadores
    grupo_regiao = folium.FeatureGroup(name=regiao)

    # filtramos as capitais daquela região
    dados_regiao = df[df["regiao"] == regiao]

    # colocamos as capitais de suas respectivas regiões no grupo indicado a elas
    for linha in dados_regiao.itertuples():

        texto_popup = f"""
        <b>{linha.capital}</b><br>
        Estado: {linha.estado}<br>
        UF: {linha.uf}<br>
        Região: {linha.regiao}<br>
        Latitude: {linha.latitude}<br>
        Longitude: {linha.longitude}
        """

        folium.Marker(
            location=[linha.latitude, linha.longitude],
            popup=texto_popup,
            tooltip=linha.capital
        ).add_to(grupo_regiao)

    # adicionamos o grupo no mapa
    grupo_regiao.add_to(mapa_regioes)

# aqui temos o controle para mostrar ou nao determinada região no mapa
folium.LayerControl(collapsed=False).add_to(mapa_regioes)


mapa_regioes

## 7) Conclusão

Criamos um mapa interativo das capitais brasileiras usando dados de um arquivo CSV.

## O que fizemos
- Carregamos uma base de dados em CSV
- Entendemos a estrutura dos dados
- Criamos filtros por região
- Criamos um mapa interativo com folium